application: giladconnect
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images
  static_dir: images
  mime_type: image/png

- url: /css
  static_dir: css
  mime_type: text/css; charset=UTF-8

- url: /fonts
  static_dir: fonts

- url: /js
  static_dir: js

- url: /sitemap.xml    
  static_files: sitemap.xml
  upload: sitemap.xml
  mime_type: application/xml

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
